### ISSUE TITLE
Issues with Antergos/Arch-based Distros

### ISSUE THREAD

**Issue by sim-s-singh** [oliverb123/scrybe#4]
While I was trying to get Scrybe working for screenshots, I have come across a couple of issues that make it so that I can not even run the program.

#### Arch/Antergos Use of `python`
 In Antergos (which is based on Arch), the `python` package is synonymous with `python3`. To actually get the program to install, you have to run `python2 setup.py`. While this will be fixed with when Scrype updates to python3, I thought it was best to inform you of it, and it should be included in the README

#### Issues with running that may due to Python
After I had run `setup.py` with `python2`, I could not get Scrybe running via the bash alias or running it manually. Both times, the output was this
```bash
sim@antergos-box $ python2 scrybe.py
Traceback (most recent call last):
  File "scrybe.py", line 3, in <module>
    userLib.Session().start()
  File "~/scrybe/userLib.py", line 8, in __init__
    self.conn = dbLib.ConnectionHandler()
  File "~/scrybe/dbLib.py", line 15, in __init__
    self.conn = sql.connect(dbName)
sqlite3.OperationalError: unable to open database file
Exception AttributeError: "ConnectionHandler instance has no attribute 'conn'" in <bound method ConnectionHandler.__del__ of <dbLib.ConnectionHandler instance at 0x7ff7e8460f38>> ignored
```
No idea what it means, but hopefully you can fix it soon.

**Comment by oliverb123** [comment]
Right now, scrybe is written in python 2. I've added a note in my todo list to add that to the readme. There is a python 3 branch that will be periodically updated with new features added to the main branch, but all development takes place in python 2 before being duplicated and updated for python 3. 

It looks to me like sql is trying to connect to a file that doesn't exist, are you sure there's a scrybe.db file where it's specified in line 14 of dbLib.py? Let me know if there isn't please, because it should have been auto created when you ran setup.py. Did you run `python2 setup.py` from inside the directory you have the repo cloned into?

**Comment by sim-s-singh** [comment]
On line 14, strangely dbName was defined as 
```bash
def __init__(self, dbName="/home/sim/testing/scrybe//home/sim/testing/scrybe//home/sim/testing/scrybe/scrybe.db"):
```
After removing the repeating /home/sim/testing/scrybe's, it works!

**Comment by oliverb123** [comment]
Hmmmm... It looks like you ran setup.py three times. Don't do this, but the setup script should stop you from doing it. Added to the todo list, thanks!
